CREATE TABLE Files
(
Id INT PRIMARY KEY IDENTITY, 
 [Name]   VARCHAR(100) NOT NULL, 
 Size     DECIMAL(18, 2) NOT NULL, 
 ParentId INT FOREIGN KEY REFERENCES Files(Id), 
 CommitId INT NOT NULL FOREIGN KEY REFERENCES Commits(Id)
)