CREATE TABLE Issues
(
 Id INT PRIMARY KEY IDENTITY, 
 Title        VARCHAR(255) NOT NULL, 
 IssueStatus  CHAR(6) NOT NULL, 
 RepositoryId INT NOT NULL FOREIGN KEY REFERENCES Repositories(Id), 
 AssigneeId   INT NOT NULL FOREIGN KEY REFERENCES Users(Id)
)